name: release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  deployments: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - run: npm i conventional-changelog-conventionalcommits@7.0.2

    - name: Conventional Changelog Action
      id: changelog
      uses: TriPSs/conventional-changelog-action@v5.3.0
      with:
        config-file-path: ./.changelog.config.js
        skip-version-file: true
        skip-commit: true
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.4
      with:
        maven-version: 3.6.3

    - name: Cache maven files
      id: maven-cache
      uses: actions/cache@v4.2.0
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: maven-

    - name: Set up JDK 17
      uses: actions/setup-java@v4.5.0
      with:
        cache: maven
        distribution: zulu
        java-version: 17

    - name: Deploy to local maven repo
      run: mvn --no-transfer-progress -Djgitver.use-version=${{ steps.changelog.outputs.version }} clean install
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#
# Do we really need to do this outside of the main build workflow?
#
    # - name: Create a GitHub release
    #   uses: ncipollo/release-action@v1
    #   with:
    #     artifacts: "target/*.war,target/CHANGELOG.md"
    #     tag: ${{ steps.changelog.outputs.tag }}
    #     name: Release ${{ steps.changelog.outputs.version }}
    #     body: ${{ steps.changelog.outputs.clean_changelog }}
    #     token: ${{ secrets.GITHUB_TOKEN }}

