name: Common Build Workflow
on:
  workflow_dispatch:
  repository_dispatch:
    types: [dependency_updated]

jobs:
  who-triggered-me:
    runs-on: ubuntu-latest
    steps:
      - name: Who triggered me?
        run: |
          echo "### This pipeline trigger summary 🚀" >> $GITHUB_STEP_SUMMARY
          echo "I was triggered by ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            echo "Triggered: ${{ github.event.client_payload.triggered_by }}" >> $GITHUB_STEP_SUMMARY
            echo '`repository_dispatch` payload:' >> $GITHUB_STEP_SUMMARY
            echo '```json' >> $GITHUB_STEP_SUMMARY
            echo '${{ toJson(github.event.client_payload) }}' | jq . >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Manual trigger" >> $GITHUB_STEP_SUMMARY
          fi

  echo-the-deets:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.client_payload.reports-version }}

  build_java:
    uses: pde-build-demo/java/.github/workflows/build.yml@main
    # defaults:
    #   run:
    #     working-directory: repos/java
    permissions:
      contents: write
      packages: write
      deployments: write


